module.exports = {
	HOSPITALS: [
		"Alberta Children's Hospital",
		"Medicine Hat Regional Hospital",
		"Red Deer Regional Hospital",
		"Chinook Regional Hospital",
		"Foothills Medical Centre",
		"Peter Lougheed Centre",
		"Rockyview General Hospital",
		"South Health Campus",
		"Fort Sask Community Hospital",
		"Grey Nuns Community Hospital",
		"Leduc Community Hospital",
		"Misericordia Community Hospital",
		"Northeast Community Health Centre",
		"Royal Alexandra Hospital",
		"Stollery Children's Hospital",
		"Strathcona Community Hospital ",
		"Sturgeon Community Hospital",
		"University of Alberta Hospital",
		"WestView Health Centre",	
	],
}